name: 'Setup Guance'

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  run-setup-guance-cli:
    name: 'Guance CLI Run'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Setup Guance
      uses: ./
      with:
        version: 0.0.2

    - name: Print Guance Version
      shell: bash
      run: guance version
